default_platform(:ios)

platform :ios do
  lane :increment_uikit do
    increment_build_number(
      xcodeproj: 'Examples/UIKitSample/UIKitSample.xcodeproj',
      build_number: number_of_commits
    )
  end

  lane :increment_swiftui do
    increment_build_number(
      xcodeproj: 'Examples/SwiftUISample/SwiftUISample.xcodeproj',
      build_number: number_of_commits
    )
  end
end

