name: danger

on: pull_request

permissions:
  pull-requests: write

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Bundle install
        run: bundle install --path vendor/bundle

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
